/**
 * This class is generated by jOOQ
 */
package org.github.rwynn.wellington.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthoritiesRecord extends org.jooq.impl.TableRecordImpl<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord> implements org.jooq.Record6<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -366570580;

	/**
	 * Setter for <code>public.authorities.username</code>. 
	 */
	public void setUsername(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.authorities.username</code>. 
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.authorities.authority</code>. 
	 */
	public void setAuthority(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.authorities.authority</code>. 
	 */
	public java.lang.String getAuthority() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.authorities.createdby</code>. 
	 */
	public void setCreatedby(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.authorities.createdby</code>. 
	 */
	public java.lang.String getCreatedby() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.authorities.createddate</code>. 
	 */
	public void setCreateddate(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.authorities.createddate</code>. 
	 */
	public java.sql.Timestamp getCreateddate() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>public.authorities.lastmodifiedby</code>. 
	 */
	public void setLastmodifiedby(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.authorities.lastmodifiedby</code>. 
	 */
	public java.lang.String getLastmodifiedby() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.authorities.lastmodifieddate</code>. 
	 */
	public void setLastmodifieddate(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.authorities.lastmodifieddate</code>. 
	 */
	public java.sql.Timestamp getLastmodifieddate() {
		return (java.sql.Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES.AUTHORITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES.CREATEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES.CREATEDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES.LASTMODIFIEDBY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES.LASTMODIFIEDDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAuthority();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCreatedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getCreateddate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getLastmodifiedby();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getLastmodifieddate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AuthoritiesRecord
	 */
	public AuthoritiesRecord() {
		super(org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES);
	}

	/**
	 * Create a detached, initialised AuthoritiesRecord
	 */
	public AuthoritiesRecord(java.lang.String username, java.lang.String authority, java.lang.String createdby, java.sql.Timestamp createddate, java.lang.String lastmodifiedby, java.sql.Timestamp lastmodifieddate) {
		super(org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES);

		setValue(0, username);
		setValue(1, authority);
		setValue(2, createdby);
		setValue(3, createddate);
		setValue(4, lastmodifiedby);
		setValue(5, lastmodifieddate);
	}
}
