/**
 * This class is generated by jOOQ
 */
package org.github.rwynn.wellington.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends org.jooq.impl.TableRecordImpl<org.github.rwynn.wellington.persistence.jooq.tables.records.UsersRecord> implements org.jooq.Record5<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, java.lang.Long> {

	private static final long serialVersionUID = -1881398213;

	/**
	 * Setter for <code>public.users.username</code>. 
	 */
	public void setUsername(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.users.username</code>. 
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.users.key</code>. 
	 */
	public void setKey(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.users.key</code>. 
	 */
	public java.lang.String getKey() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.users.locked</code>. 
	 */
	public void setLocked(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.users.locked</code>. 
	 */
	public java.lang.Boolean getLocked() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>public.users.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.users.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.users.version</code>. 
	 */
	public void setVersion(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.users.version</code>. 
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, java.lang.Long> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Integer, java.lang.Long> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Users.USERS.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Users.USERS.KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Users.USERS.LOCKED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Users.USERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return org.github.rwynn.wellington.persistence.jooq.tables.Users.USERS.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getLocked();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getVersion();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(org.github.rwynn.wellington.persistence.jooq.tables.Users.USERS);
	}

	/**
	 * Create a detached, initialised UsersRecord
	 */
	public UsersRecord(java.lang.String username, java.lang.String key, java.lang.Boolean locked, java.lang.Integer id, java.lang.Long version) {
		super(org.github.rwynn.wellington.persistence.jooq.tables.Users.USERS);

		setValue(0, username);
		setValue(1, key);
		setValue(2, locked);
		setValue(3, id);
		setValue(4, version);
	}
}
