/**
 * This class is generated by jOOQ
 */
package org.github.rwynn.wellington.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authorities extends org.jooq.impl.TableImpl<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord> {

	private static final long serialVersionUID = -1192827870;

	/**
	 * The singleton instance of <code>public.authorities</code>
	 */
	public static final org.github.rwynn.wellington.persistence.jooq.tables.Authorities AUTHORITIES = new org.github.rwynn.wellington.persistence.jooq.tables.Authorities();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord> getRecordType() {
		return org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord.class;
	}

	/**
	 * The column <code>public.authorities.username</code>. 
	 */
	public final org.jooq.TableField<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(80).nullable(false), this);

	/**
	 * The column <code>public.authorities.authority</code>. 
	 */
	public final org.jooq.TableField<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord, java.lang.String> AUTHORITY = createField("authority", org.jooq.impl.SQLDataType.VARCHAR.length(80).nullable(false), this);

	/**
	 * The column <code>public.authorities.createdby</code>. 
	 */
	public final org.jooq.TableField<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord, java.lang.String> CREATEDBY = createField("createdby", org.jooq.impl.SQLDataType.VARCHAR.length(80), this);

	/**
	 * The column <code>public.authorities.createddate</code>. 
	 */
	public final org.jooq.TableField<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord, java.sql.Timestamp> CREATEDDATE = createField("createddate", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>public.authorities.lastmodifiedby</code>. 
	 */
	public final org.jooq.TableField<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord, java.lang.String> LASTMODIFIEDBY = createField("lastmodifiedby", org.jooq.impl.SQLDataType.VARCHAR.length(80), this);

	/**
	 * The column <code>public.authorities.lastmodifieddate</code>. 
	 */
	public final org.jooq.TableField<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord, java.sql.Timestamp> LASTMODIFIEDDATE = createField("lastmodifieddate", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>public.authorities</code> table reference
	 */
	public Authorities() {
		super("authorities", org.github.rwynn.wellington.persistence.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.authorities</code> table reference
	 */
	public Authorities(java.lang.String alias) {
		super(alias, org.github.rwynn.wellington.persistence.jooq.Public.PUBLIC, org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.github.rwynn.wellington.persistence.jooq.tables.records.AuthoritiesRecord, ?>>asList(org.github.rwynn.wellington.persistence.jooq.Keys.AUTHORITIES__FK_AUTHORITIES_USERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.github.rwynn.wellington.persistence.jooq.tables.Authorities as(java.lang.String alias) {
		return new org.github.rwynn.wellington.persistence.jooq.tables.Authorities(alias);
	}
}
