/**
 * This class is generated by jOOQ
 */
package org.github.rwynn.wellington.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Databasechangeloglock extends org.jooq.impl.TableImpl<org.github.rwynn.wellington.persistence.jooq.tables.records.DatabasechangeloglockRecord> {

	private static final long serialVersionUID = 1129442548;

	/**
	 * The singleton instance of <code>public.databasechangeloglock</code>
	 */
	public static final org.github.rwynn.wellington.persistence.jooq.tables.Databasechangeloglock DATABASECHANGELOGLOCK = new org.github.rwynn.wellington.persistence.jooq.tables.Databasechangeloglock();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.github.rwynn.wellington.persistence.jooq.tables.records.DatabasechangeloglockRecord> getRecordType() {
		return org.github.rwynn.wellington.persistence.jooq.tables.records.DatabasechangeloglockRecord.class;
	}

	/**
	 * The column <code>public.databasechangeloglock.id</code>. 
	 */
	public final org.jooq.TableField<org.github.rwynn.wellington.persistence.jooq.tables.records.DatabasechangeloglockRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.databasechangeloglock.locked</code>. 
	 */
	public final org.jooq.TableField<org.github.rwynn.wellington.persistence.jooq.tables.records.DatabasechangeloglockRecord, java.lang.Boolean> LOCKED = createField("locked", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this);

	/**
	 * The column <code>public.databasechangeloglock.lockgranted</code>. 
	 */
	public final org.jooq.TableField<org.github.rwynn.wellington.persistence.jooq.tables.records.DatabasechangeloglockRecord, java.sql.Timestamp> LOCKGRANTED = createField("lockgranted", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>public.databasechangeloglock.lockedby</code>. 
	 */
	public final org.jooq.TableField<org.github.rwynn.wellington.persistence.jooq.tables.records.DatabasechangeloglockRecord, java.lang.String> LOCKEDBY = createField("lockedby", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>public.databasechangeloglock</code> table reference
	 */
	public Databasechangeloglock() {
		super("databasechangeloglock", org.github.rwynn.wellington.persistence.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.databasechangeloglock</code> table reference
	 */
	public Databasechangeloglock(java.lang.String alias) {
		super(alias, org.github.rwynn.wellington.persistence.jooq.Public.PUBLIC, org.github.rwynn.wellington.persistence.jooq.tables.Databasechangeloglock.DATABASECHANGELOGLOCK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.github.rwynn.wellington.persistence.jooq.tables.records.DatabasechangeloglockRecord> getPrimaryKey() {
		return org.github.rwynn.wellington.persistence.jooq.Keys.PK_DATABASECHANGELOGLOCK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.github.rwynn.wellington.persistence.jooq.tables.records.DatabasechangeloglockRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.github.rwynn.wellington.persistence.jooq.tables.records.DatabasechangeloglockRecord>>asList(org.github.rwynn.wellington.persistence.jooq.Keys.PK_DATABASECHANGELOGLOCK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.github.rwynn.wellington.persistence.jooq.tables.Databasechangeloglock as(java.lang.String alias) {
		return new org.github.rwynn.wellington.persistence.jooq.tables.Databasechangeloglock(alias);
	}
}
