/**
 * This class is generated by jOOQ
 */
package org.github.rwynn.wellington.persistence.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 333601576;

	/**
	 * The singleton instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			org.github.rwynn.wellington.persistence.jooq.Sequences.USERS_ID_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES,
			org.github.rwynn.wellington.persistence.jooq.tables.Databasechangelog.DATABASECHANGELOG,
			org.github.rwynn.wellington.persistence.jooq.tables.Databasechangeloglock.DATABASECHANGELOGLOCK,
			org.github.rwynn.wellington.persistence.jooq.tables.Users.USERS);
	}
}
