/**
 * This class is generated by jOOQ
 */
package org.github.rwynn.wellington.persistence.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.users_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> USERS_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("users_id_seq", org.github.rwynn.wellington.persistence.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
