/**
 * This class is generated by jOOQ
 */
package org.github.rwynn.wellington.persistence.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.authorities
	 */
	public static final org.github.rwynn.wellington.persistence.jooq.tables.Authorities AUTHORITIES = org.github.rwynn.wellington.persistence.jooq.tables.Authorities.AUTHORITIES;

	/**
	 * The table public.databasechangelog
	 */
	public static final org.github.rwynn.wellington.persistence.jooq.tables.Databasechangelog DATABASECHANGELOG = org.github.rwynn.wellington.persistence.jooq.tables.Databasechangelog.DATABASECHANGELOG;

	/**
	 * The table public.databasechangeloglock
	 */
	public static final org.github.rwynn.wellington.persistence.jooq.tables.Databasechangeloglock DATABASECHANGELOGLOCK = org.github.rwynn.wellington.persistence.jooq.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

	/**
	 * The table public.users
	 */
	public static final org.github.rwynn.wellington.persistence.jooq.tables.Users USERS = org.github.rwynn.wellington.persistence.jooq.tables.Users.USERS;
}
